### ISSUE TITLE
Non-Deterministic Behavior and POA Craziness

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbccs#49] opened 2015-08-13 07:04 UTC

**Comment by nlhepler** [comment] 2015-08-13 07:19
Dave was looking into POA nondeterminism, but IIRC, it isn't addressable until we write our own graph class to take over for boost's. =/ @dalexander, can you chime in?

I've been looking at how the C# POA reorders subreads. @evolvedmicrobe, let's talk tomorrow about what it does and whether we should replicate/iterate?

**Comment by dalexander** [comment] 2015-08-13 13:51
The POA should be deterministic as of my fix to ConsensusCore a month or two ago.  If you have a test case that shows the exact same inputs to the POA (including ordering) giving different output, then we know the problem is in the POA, but otherwise I am skeptical.

It might be useful for debugging to have some flag like "--poaOnly" that just dumps the POA as the consensus.

This issue highlights the need for some end-to-end tests / cram tests, this kind of thing should be found automatically.

**Comment by dalexander** [comment] 2015-08-13 14:19
^^ Grumpy pre-coffee post.  I suspect the ordering is the problem... but if not, please reduce the problem to a failing test case and I will look into the POA.

**Comment by dalexander** [comment] 2015-08-13 14:21
@nlhepler, could you tag the "pre-patch" and "post-patch" versions as alpha-1, alpha-2, or some such?

**Comment by nlhepler** [comment] 2015-08-13 16:44
@dalexander, not grumpy at all, very good points made. =) As for ordering, it is deterministic: polymerase order. This is doubtlessly suboptimal, and we'll look into it. What was done in C# is pretty straightforward, but I think we should go even further--again, we'll discuss later.

End-to-end tests are definitely in order.

**Comment by nlhepler** [comment] 2015-08-14 04:49
There's something wonky going on. I'm going to spend tomorrow trying to track it down. For zmws 1-10000 of the lambda dataset I've been playing with, between two runs of the same binary there's 3 additional sequences and 17 other sequences that differ in length/content/QVs.

**Comment by nlhepler** [comment] 2015-08-14 14:59
Did another run, differs from the previous two runs by 2 sequences. All of them can be traced to convergence failures. As that's a separate issue, I'm going to focus on the sequence content nondeterminism here.

**Comment by nlhepler** [comment] 2015-08-14 18:16
Okay, the POA is definitely a culprit. Narrowing now.

**Comment by nlhepler** [comment] 2015-08-14 19:40
Subread input order is deterministic--seems the POA sometimes has issues. Over 10 runs of m141115_075238_ethan_c100699872550000001823139203261572_s1_p0/915, I observed 3 different species. Given the species, the subread extents were deterministic.

**Comment by nlhepler** [comment] 2015-08-14 20:07
Added a test to the poaFixes branch. https://github.com/PacificBiosciences/pbccs/commit/6af8f4870df0dc2fded31e80618b46ce970055cb

**Comment by nlhepler** [comment] 2015-08-15 21:05
Saturday status update: okay, been digging at this--it seems that there are differences in the intermediate consensus leading to differences in the anchors found by the SparsePoa. Tracking it further, it seems that the first difference arises in the graph in ReachingScore, which seems to induce an alternative traversal. Investigation ongoing.

**Comment by nlhepler** [comment] 2015-08-15 21:19
Further narrowing suggests the first difference arises in SpanningReads, beginning with tagSpan. I think that the topological_sort is ordering the end arbitrarily within its topological group, leading to nondeterministic behavior.

**Comment by evolvedmicrobe** [comment] 2015-08-15 21:37
Does topological sort only guarantee that if in a DAG edge *(u,v)* exists, then *u* will come before *v* in the sort, but make no other guarantees on the order (this could make it the non-deterministic step and we could perhaps apply an additional sort criteria to guarantee that for a given graph structure the sort order was the same?).

**Comment by nlhepler** [comment] 2015-08-15 21:50
@evolvedmicrobe, it only guarantees u before v the way we're invoking it. I'm trying to figure out if it can be invoked with further constraints..

**Comment by nlhepler** [comment] 2015-08-15 22:11
Okay, no way to use topo_sort for this (deterministically or correctly). Going to need a modified DFS. @dalexander, can you chime in at your earliest convenience? We actually don't want topo_sort here, I think. We want all edges in all paths between start and end, yah?

**Comment by nlhepler** [comment] 2015-08-15 22:35
Okay, two possibilities: do the tagSpan operation separately as it is now, or integrate it with threadFirstRead and tracebackAndThread. I think the latter might actually be saner.

**Comment by nlhepler** [comment] 2015-08-15 23:29
I'm testing a fix locally. It appears to work at first pass, just need to make sure the PoaTests all pass everywhere, and then I'll post it in this branch for @dalexander to review.

**Comment by nlhepler** [comment] 2015-08-15 23:46
Hmm, I realize integrating it into threadFirstRead and tracebackAndThread isn't technically correct (for the semantic of SpanningReads as I understand it). Going to have to revert it and focus on the DFS solution..

**Comment by nlhepler** [comment] 2015-08-17 01:54
I removed the test because it's not failing on CircleCI and we can't afford to increase the number of runs. The memory allocations seem more deterministic in the CircleCI environment, which doesn't help us with this failure mode.. Despite this, most of nondeterminism seems to have been identified and addressed. I'm running a larger suite of tests now, but the initial results are promising.

**Comment by nlhepler** [comment] 2015-08-17 01:55
You can see the most recent work [here](https://github.com/nlhepler/pbccs/tree/poaFixes)

**Comment by nlhepler** [comment] 2015-08-17 05:59
This is fixed as of bfcbe492d832556f1e61b1224a9f5018303a9a0a

**Closed by nlhepler** 2015-08-17 05:59 UTC
Labels: bug

**Comment by dalexander** [comment] 2015-08-17 14:34
@nlhepler, I think we lost your "summary" comment when you deleted the branch.  Can you repeat it here?

**Comment by nlhepler** [comment] 2015-08-17 14:53
@evolvedmicrobe, @dalexander, did either of you get an email with it therein?

**Comment by dalexander** [comment] 2015-08-17 15:46
found it:

@dalexander, two things. There were three places where we were finding a maximum in an arbitrarily ordered sequence, and we didn't handle the case of equivalent values in the sequence in a deterministic way. The other was tagSpan, which used a topological sort. First, the ordering outside of the (u,v) u-before-v constraint is nondeterministic. As a result, if you had A->B; A->C; B->D; C->D; B->E; E->F, where A,B,C,D are a diamond and E,F are a dangling fork off of B, then E and F could appear before D in the topo sort and change SpanningReads in A) the wrong way, and B) a nondeterministic way. I fixed this by using a couple DFS's, see SpanningReads in PoaGraphTraversals.cpp

**Comment by dalexander** [comment] 2015-08-17 15:46
in the future, please leave the branch open til review complete
